import type { HarnessConfig } from '../../types/index.js';
import { writeText, ensureDir, resolvePath } from '../../utils/index.js';

export interface GeneratedFiles {
  'CLAUDE.md': string;
  '.claude/conventions.md': string;
  '.claude/tech-stack.md': string;
  '.claude/workflow.md': string;
  '.claude/coding-principles.md': string;
}

export async function generateClaudeRules(root: string, config: HarnessConfig): Promise<GeneratedFiles> {
  const claudeDir = resolvePath(root, '.claude');
  await ensureDir(claudeDir);

  const files: GeneratedFiles = {
    'CLAUDE.md': buildClaudeMd(config),
    '.claude/conventions.md': buildConventions(config),
    '.claude/tech-stack.md': buildTechStack(config),
    '.claude/workflow.md': buildWorkflow(config),
    '.claude/coding-principles.md': buildCodingPrinciples(),
  };

  for (const [path, content] of Object.entries(files)) {
    await writeText(resolvePath(root, path), content);
  }

  return files;
}

export async function generateClaudeMd(root: string, config: HarnessConfig): Promise<string> {
  const content = buildClaudeMd(config);
  await writeText(resolvePath(root, 'CLAUDE.md'), content);
  return content;
}

// ─── CLAUDE.md — 메인 컨텍스트 (프로젝트 개요 + 참조 안내) ───

function buildClaudeMd(config: HarnessConfig): string {
  const lines: string[] = [];

  lines.push(`# ${config.project.name}`);
  lines.push('');
  lines.push('> Auto-generated by @wonseok-han/harness-core');
  lines.push('');

  lines.push('## Project');
  lines.push(`- **Framework:** ${config.project.framework}`);
  lines.push(`- **Language:** ${config.project.language}`);
  lines.push(`- **Package Manager:** ${config.project.packageManager}`);
  lines.push(`- **Architecture:** ${config.architecture.style}`);
  lines.push('');

  lines.push('## Rules');
  lines.push('- See `.claude/conventions.md` for code conventions and import rules');
  lines.push('- See `.claude/tech-stack.md` for tools and dependencies');
  lines.push('- See `.claude/workflow.md` for development workflow and commands');
  lines.push('');

  lines.push('## Agent');
  lines.push(`- Persona: ${config.agent.persona}`);
  lines.push(`- Allowed scopes: ${config.agent.allowedScopes.join(', ')}`);
  lines.push('- Do NOT modify files outside allowed scopes without explicit permission');
  lines.push('');
  lines.push('## Coding Principles');
  lines.push('');
  lines.push('See `.claude/coding-principles.md` for behavioral guidelines.');

  return lines.join('\n') + '\n';
}

// ─── .claude/coding-principles.md — AI 행동 원칙 ───

function buildCodingPrinciples(): string {
  return `# Coding Principles

Behavioral guidelines to reduce common LLM coding mistakes.
Based on [Andrej Karpathy's guidelines](https://github.com/multica-ai/andrej-karpathy-skills).

## 1. Think Before Coding

**Don't assume. Don't hide confusion. Surface tradeoffs.**

- State your assumptions explicitly. If uncertain, ask.
- If multiple interpretations exist, present them — don't pick silently.
- If a simpler approach exists, say so. Push back when warranted.
- If something is unclear, stop. Name what's confusing. Ask.

## 2. Simplicity First

**Minimum code that solves the problem. Nothing speculative.**

- No features beyond what was asked.
- No abstractions for single-use code.
- No "flexibility" or "configurability" that wasn't requested.
- No error handling for impossible scenarios.
- If you write 200 lines and it could be 50, rewrite it.

## 3. Surgical Changes

**Touch only what you must. Clean up only your own mess.**

- Don't "improve" adjacent code, comments, or formatting.
- Don't refactor things that aren't broken.
- Match existing style, even if you'd do it differently.
- If you notice unrelated dead code, mention it — don't delete it.
- Remove imports/variables/functions that YOUR changes made unused.
- Every changed line should trace directly to the user's request.

## 4. Goal-Driven Execution

**Define success criteria. Loop until verified.**

Transform tasks into verifiable goals:
- "Add validation" → Write tests for invalid inputs, then make them pass
- "Fix the bug" → Write a test that reproduces it, then make it pass
- "Refactor X" → Ensure tests pass before and after

For multi-step tasks, state a brief plan:
\`\`\`
1. [Step] → verify: [check]
2. [Step] → verify: [check]
3. [Step] → verify: [check]
\`\`\`
`;
}

// ─── .claude/conventions.md — 아키텍처 & 코딩 컨벤션 ───

function buildConventions(config: HarnessConfig): string {
  const lines: string[] = [];

  lines.push('# Conventions');
  lines.push('');

  lines.push('## Architecture');
  lines.push(`- Style: **${config.architecture.style}**`);
  if (config.architecture.enforceIndexGen) {
    lines.push('- Every directory under `src/` MUST have an `index.ts` barrel export');
  }
  lines.push('');

  if (Object.keys(config.architecture.forbiddenImports).length > 0) {
    lines.push('## Import Restrictions');
    lines.push('');
    for (const [source, forbidden] of Object.entries(config.architecture.forbiddenImports)) {
      lines.push(`- \`${source}\` MUST NOT import from: ${forbidden.map((f) => `\`${f}\``).join(', ')}`);
    }
    lines.push('');
  }

  lines.push('## File Naming');
  lines.push('- Components: PascalCase (`UserProfile.tsx`)');
  lines.push('- Hooks: camelCase with `use` prefix (`useAuth.ts`)');
  lines.push('- Utils/Services: camelCase (`formatDate.ts`, `authService.ts`)');
  lines.push('- Tests: same name + `.test` suffix (`UserProfile.test.tsx`)');
  lines.push('');

  lines.push('## Testing');
  if (config.testing.requireTestFileWithImplementation) {
    lines.push('- Every implementation file MUST have a corresponding `.test` file');
  }
  lines.push(`- Minimum coverage: statements=${config.testing.minCoverage.statements}%, branches=${config.testing.minCoverage.branches}%`);

  return lines.join('\n') + '\n';
}

// ─── .claude/tech-stack.md — 기술 스택 & 도구 ───

function buildTechStack(config: HarnessConfig): string {
  const lines: string[] = [];

  lines.push('# Tech Stack');
  lines.push('');

  lines.push('## Core');
  lines.push(`- Framework: ${config.project.framework}`);
  lines.push(`- Language: ${config.project.language}`);
  lines.push(`- Package Manager: ${config.project.packageManager}`);
  lines.push('');

  lines.push('## Development');
  lines.push(`- Linter: ${config.development.linter}`);
  lines.push(`- Formatter: ${config.development.formatter}`);
  if (config.development.styling) {
    lines.push(`- Styling: ${config.development.styling}`);
  }
  lines.push('');

  lines.push('## Testing');
  lines.push(`- Runner: ${config.testing.runner}`);

  return lines.join('\n') + '\n';
}

// ─── .claude/workflow.md — 개발 워크플로우 & CLI 명령어 ───

function buildWorkflow(config: HarnessConfig): string {
  const lines: string[] = [];

  lines.push('# Development Workflow');
  lines.push('');

  lines.push('## Commands');
  lines.push('```bash');
  lines.push('harness analyze              # Define domain glossary & feature specs');
  lines.push('harness sync                 # Sync architecture rules & check violations');
  lines.push('harness sync --check         # Check-only mode (CI / pre-commit)');
  lines.push('harness sync --watch         # Auto-sync on config change (run with dev server)');
  lines.push('harness generate <type> <n>  # Scaffold: component, hook, util, service, model');
  lines.push('harness test                 # Run tests with self-healing feedback loop');
  lines.push('harness test --coverage      # Run with coverage reporting');
  lines.push('```');
  lines.push('');

  lines.push('## Scaffolding');
  lines.push('Always use `harness generate` to create new files:');
  lines.push('```bash');
  lines.push('harness generate component UserProfile');
  lines.push('harness generate hook useAuth');
  lines.push('harness generate service payment');
  lines.push('harness generate util format-date');
  lines.push('harness generate model user');
  lines.push('```');
  lines.push('');

  lines.push('## Pre-commit');
  lines.push(`- Linter: \`${config.development.linter}\` runs on staged files`);
  lines.push(`- Formatter: \`${config.development.formatter}\``);
  lines.push('- TypeScript type check: `tsc --noEmit`');
  lines.push('');

  lines.push('## Pre-push');
  lines.push('- Full test suite: `harness test`');

  return lines.join('\n') + '\n';
}
