import type { HarnessConfig } from '../../types/index.js';
import type { AgentAdapter, GeneratedOutput } from './types.js';
import { buildProjectContext, buildConventionRules, buildWorkflowRules, buildToolsSection } from './shared.js';
import { writeText, resolvePath } from '../../utils/index.js';

export const aiderAdapter: AgentAdapter = {
  name: 'Aider',
  type: 'aider',

  async generate(root: string, config: HarnessConfig): Promise<GeneratedOutput> {
    const files: Record<string, string> = {};

    // CONVENTIONS.md (Aider reads --read files)
    const conventions = [
      buildProjectContext(config),
      buildConventionRules(config),
      buildWorkflowRules(config),
      buildToolsSection(config),
    ].join('\n');
    files['CONVENTIONS.md'] = conventions;

    // .aider.conf.yml
    const aiderConf = [
      '# Auto-generated by @wonseok-han/harness-core',
      'read:',
      '  - CONVENTIONS.md',
      '  - harness.config.json',
      ...(await hasGlossary(root) ? ['  - domain-glossary.json'] : []),
      `lint-cmd: ${getLintCommand(config)}`,
      `test-cmd: npx harness test --root .`,
      'auto-lint: true',
      'auto-test: true',
    ].join('\n');
    files['.aider.conf.yml'] = aiderConf;

    for (const [path, content] of Object.entries(files)) {
      await writeText(resolvePath(root, path), content);
    }

    return {
      files,
      description: 'CONVENTIONS.md + .aider.conf.yml (auto-lint, auto-test enabled)',
    };
  },
};

async function hasGlossary(root: string): Promise<boolean> {
  const { fileExists } = await import('../../utils/index.js');
  return fileExists(resolvePath(root, 'domain-glossary.json'));
}

function getLintCommand(config: HarnessConfig): string {
  if (config.development.linter === 'biome') return 'npx @biomejs/biome check .';
  return 'npx eslint src/';
}
