import type { HarnessConfig } from '../../types/index.js';
import type { AgentAdapter, GeneratedOutput } from './types.js';
import { buildProjectContext, buildConventionRules, buildWorkflowRules, buildCodingPrinciplesSection, buildCustomCodingStandards, buildToolsSection } from './shared.js';
import { writeText, resolvePath, fileExists } from '../../utils/index.js';

export const aiderAdapter: AgentAdapter = {
  name: 'Aider',
  type: 'aider',

  async generate(root: string, config: HarnessConfig): Promise<GeneratedOutput> {
    const files: Record<string, string> = {};
    const skipped: string[] = [];

    const hasConventions = await fileExists(resolvePath(root, 'CONVENTIONS.md'));
    const hasAiderConf = await fileExists(resolvePath(root, '.aider.conf.yml'));

    if (hasConventions) {
      skipped.push('CONVENTIONS.md');
    } else {
      const conventions = [
        buildProjectContext(config),
        buildConventionRules(config),
        buildCustomCodingStandards(config),
        buildWorkflowRules(config),
        buildCodingPrinciplesSection(),
        buildToolsSection(config),
      ].join('\n');
      files['CONVENTIONS.md'] = conventions;
    }

    if (hasAiderConf) {
      skipped.push('.aider.conf.yml');
    } else {
      const aiderConf = [
        '# Auto-generated by @wonseok-han/harness-core',
        'read:',
        '  - CONVENTIONS.md',
        '  - harness.config.json',
        ...(await hasGlossary(root) ? ['  - domain-glossary.json'] : []),
        `lint-cmd: ${getLintCommand(config)}`,
        `test-cmd: npx harness test --root .`,
        'auto-lint: true',
        'auto-test: true',
      ].join('\n');
      files['.aider.conf.yml'] = aiderConf;
    }

    for (const [path, content] of Object.entries(files)) {
      await writeText(resolvePath(root, path), content);
    }

    const created = Object.keys(files).join(' + ') || 'none';
    const desc = skipped.length > 0
      ? `${created}${created !== 'none' ? ' ' : ''}(existing ${skipped.join(', ')} preserved)`
      : 'CONVENTIONS.md + .aider.conf.yml (auto-lint, auto-test enabled)';

    return {
      files,
      skipped: skipped.length > 0 ? skipped : undefined,
      description: desc,
    };
  },
};

async function hasGlossary(root: string): Promise<boolean> {
  const { fileExists } = await import('../../utils/index.js');
  return fileExists(resolvePath(root, 'domain-glossary.json'));
}

function getLintCommand(config: HarnessConfig): string {
  if (config.development.linter === 'biome') return 'npx @biomejs/biome check .';
  return 'npx eslint src/';
}
