import type { HarnessConfig } from '../../types/index.js';
import type { AgentAdapter, GeneratedOutput } from './types.js';
import { buildProjectContext, buildConventionRules, buildWorkflowRules, buildToolsSection } from './shared.js';
import { generateClaudeHooks } from '../policy/hooks/generator.js';
import { writeText, ensureDir, resolvePath } from '../../utils/index.js';

export const claudeAdapter: AgentAdapter = {
  name: 'Claude Code',
  type: 'claude',

  async generate(root: string, config: HarnessConfig): Promise<GeneratedOutput> {
    const files: Record<string, string> = {};

    // CLAUDE.md
    const claudeMd = [
      buildProjectContext(config),
      '> Auto-generated by @wonseok-han/harness-core\n',
      buildToolsSection(config),
      'See `.claude/conventions.md`, `.claude/tech-stack.md`, `.claude/workflow.md` for details.\n',
    ].join('\n');
    files['CLAUDE.md'] = claudeMd;

    // .claude/conventions.md
    files['.claude/conventions.md'] = `# Conventions\n\n${buildConventionRules(config)}`;

    // .claude/tech-stack.md
    files['.claude/tech-stack.md'] = `# Tech Stack\n\n${buildToolsSection(config)}`;

    // .claude/workflow.md
    files['.claude/workflow.md'] = `# Workflow\n\n${buildWorkflowRules(config)}`;

    // Write files
    for (const [path, content] of Object.entries(files)) {
      const fullPath = resolvePath(root, path);
      await ensureDir(resolvePath(fullPath, '..'));
      await writeText(fullPath, content);
    }

    // Generate Claude-specific hooks (.claude/hooks/ + .claude/settings.json)
    await generateClaudeHooks(root, config);

    return {
      files,
      description: 'CLAUDE.md + .claude/*.md + .claude/hooks/ + .claude/settings.json (auto-enforcement via Claude Code Hooks)',
    };
  },
};
