import type { HarnessConfig } from '../../types/index.js';
import type { AgentAdapter, GeneratedOutput } from './types.js';
import { buildProjectContext, buildConventionRules, buildWorkflowRules, buildCodingPrinciplesSection, buildCustomCodingStandards, buildToolsSection } from './shared.js';
import { generateClaudeHooks } from '../policy/hooks/generator.js';
import { writeText, ensureDir, resolvePath, fileExists } from '../../utils/index.js';

function wrapMdc(description: string, content: string): string {
  return `---\ndescription: ${description}\nalwaysApply: true\n---\n\n${content}`;
}

export const claudeAdapter: AgentAdapter = {
  name: 'Claude Code',
  type: 'claude',

  async generate(root: string, config: HarnessConfig): Promise<GeneratedOutput> {
    const files: Record<string, string> = {};
    const skipped: string[] = [];

    const hasRootClaudeMd = await fileExists(resolvePath(root, 'CLAUDE.md'));
    const hasDotClaudeMd = await fileExists(resolvePath(root, '.claude', 'CLAUDE.md'));

    if (hasRootClaudeMd || hasDotClaudeMd) {
      const existing = hasRootClaudeMd ? 'CLAUDE.md' : '.claude/CLAUDE.md';
      skipped.push(existing);
    } else {
      const claudeMd = [
        buildProjectContext(config),
        '> Auto-generated by @wonseok-han/harness-core\n',
        buildToolsSection(config),
      ].join('\n');
      files['CLAUDE.md'] = claudeMd;
    }

    // .claude/rules/*.mdc — alwaysApply: true, auto-loaded by Claude Code
    const customStandards = buildCustomCodingStandards(config);
    files['.claude/rules/harness-conventions.mdc'] = wrapMdc(
      'Project conventions and coding standards enforced by harness-core',
      `${buildProjectContext(config)}# Conventions\n\n${buildConventionRules(config)}${customStandards}`,
    );

    files['.claude/rules/harness-tech-stack.mdc'] = wrapMdc(
      'Tech stack and tooling configuration',
      `# Tech Stack\n\n${buildToolsSection(config)}`,
    );

    files['.claude/rules/harness-workflow.mdc'] = wrapMdc(
      'Development workflow rules and scaffolding guidelines',
      `# Workflow\n\n${buildWorkflowRules(config)}`,
    );

    files['.claude/rules/harness-principles.mdc'] = wrapMdc(
      'Coding principles and best practices',
      buildCodingPrinciplesSection(),
    );

    // Write files
    for (const [path, content] of Object.entries(files)) {
      const fullPath = resolvePath(root, path);
      await ensureDir(resolvePath(fullPath, '..'));
      await writeText(fullPath, content);
    }

    // Generate Claude-specific hooks (.claude/hooks/ + .claude/settings.json)
    await generateClaudeHooks(root, config);

    const parts = skipped.length > 0
      ? `.claude/rules/*.mdc + .claude/hooks/ + .claude/settings.json (existing ${skipped[0]} preserved)`
      : 'CLAUDE.md + .claude/rules/*.mdc + .claude/hooks/ + .claude/settings.json';

    return {
      files,
      skipped: skipped.length > 0 ? skipped : undefined,
      description: parts,
    };
  },
};
