import type { HarnessConfig } from '../../types/index.js';
import type { AgentAdapter, GeneratedOutput } from './types.js';
import { buildProjectContext, buildConventionRules, buildWorkflowRules, buildCodingPrinciplesSection, buildToolsSection } from './shared.js';
import { writeText, resolvePath } from '../../utils/index.js';

export const genericAdapter: AgentAdapter = {
  name: 'Generic (any AI agent)',
  type: 'generic',

  async generate(root: string, config: HarnessConfig): Promise<GeneratedOutput> {
    const files: Record<string, string> = {};

    // AI_CONTEXT.md — universal instruction file any agent can read
    const context = [
      buildProjectContext(config),
      '> Auto-generated by @wonseok-han/harness-core. Feed this file to your AI agent.\n',
      buildConventionRules(config),
      buildWorkflowRules(config),
      buildCodingPrinciplesSection(),
      buildToolsSection(config),
    ].join('\n');
    files['AI_CONTEXT.md'] = context;

    for (const [path, content] of Object.entries(files)) {
      await writeText(resolvePath(root, path), content);
    }

    return {
      files,
      description: 'AI_CONTEXT.md (universal — feed to any AI agent)',
    };
  },
};
