import type { HarnessConfig } from '../../types/index.js';
import type { AgentAdapter, GeneratedOutput } from './types.js';
import { buildProjectContext, buildConventionRules, buildWorkflowRules, buildCodingPrinciplesSection, buildCustomCodingStandards, buildToolsSection } from './shared.js';
import { writeText, resolvePath, fileExists } from '../../utils/index.js';

export const genericAdapter: AgentAdapter = {
  name: 'Generic (any AI agent)',
  type: 'generic',

  async generate(root: string, config: HarnessConfig): Promise<GeneratedOutput> {
    const files: Record<string, string> = {};
    const skipped: string[] = [];

    const hasExisting = await fileExists(resolvePath(root, 'AI_CONTEXT.md'));

    if (hasExisting) {
      skipped.push('AI_CONTEXT.md');
    } else {
      const context = [
        buildProjectContext(config),
        '> Auto-generated by @wonseok-han/harness-core. Feed this file to your AI agent.\n',
        buildConventionRules(config),
        buildCustomCodingStandards(config),
        buildWorkflowRules(config),
        buildCodingPrinciplesSection(),
        buildToolsSection(config),
      ].join('\n');
      files['AI_CONTEXT.md'] = context;

      await writeText(resolvePath(root, 'AI_CONTEXT.md'), files['AI_CONTEXT.md']);
    }

    const desc = skipped.length > 0
      ? `skipped (existing AI_CONTEXT.md preserved)`
      : 'AI_CONTEXT.md (universal — feed to any AI agent)';

    return {
      files,
      skipped: skipped.length > 0 ? skipped : undefined,
      description: desc,
    };
  },
};
